### ISSUE TITLE
jobs are not saved

### ISSUE THREAD

**Issue by emmanuelmathot** [jbox-web/redmine_jenkins#8]
In the "Add a job" popup with the "job Name" and "repository", when I click "Save", nothing happens.

**Comment by luismaia** [comment]
I have exactly the same problem.
After debugging, at least in my case, this was caused by the following error:

ActiveRecord::StatementInvalid (Mysql2::Error: Column 'comment' cannot be null: INSERT INTO `jenkins_build_changesets` (`comment`, `jenkins_build_id`, `repository_id`, `revision`) VALUES (NULL, 28, 5, '14604'))

In my case the Jenkins server sends no information about the comment.

**Comment by n-rodriguez** [comment]
Fixed by PR https://github.com/jbox-web/redmine_jenkins/pull/11
